name: test ssh command
on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/**'
      - 'tests/**'
      - 'src/**'
      - 'config/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/u0/github/CICD-demo &&
            git pull &&
            pnpm i &&
            npm run build &&
            cp -r ./dist/*  /opt/docker/nginx/1.23.1/html
